### ISSUE TITLE
Memory.cs not found

### ISSUE THREAD

**Issue by wellrcosta** [ja0117/Mainware-CSharp-Cheat-SlimDX-Overlay-#1]
Hi. The file memory.cs isn't found

**Comment by Zaczero** [comment]
He basically says that in the description:
"A Cheat coded in C# for CS:GO with updating offsets. Does NOT include the memory Read/Write class!"

Why would u even release a half-working code @ja0117 ;)

**Comment by ja0117** [comment]
Because I'm using the memory class in another version aswell. I didn't want that publicly accessible @Zaczero
